const semantic = {
  accent: {
    bolder: '#166321',
    bold: '#1C822C',
    normal: '#25A839',
    neutral: '#56BC66',
    alternative: '#7ECB8A',
    subtle: '#CDEBD2',
    subtler: '#E1F3E3',
    subtlest: '#F5FBF6',
  },
  stroke: {
    bold: '#4B4B4B',
    normal: '#808080',
    neutral: '#9D9D9D',
    alternative: '#B4B4B4',
    assistive: '#CBCBCB',
    subtle: '#E2E2E2',
    subtler: '#F9F9F9',
  },
  bg: {
    standard: '#FFFFFF',
    deep: '#F9F9F9',
    deeper: '#EDEDED',
  },
  object: {
    boldest: '#282828',
    bold: '#4B4B4B',
    normal: '#919191',
    subtle: '#BFBFBF',
    subtler: '#EDEDED',
    inverse: '#FFFFFF',
  },
  feedback: {
    error: {
      bolder: '#911E1E',
      bold: '#BD2727',
      normal: '#F53333',
      neutral: '#F76161',
      alternative: '#F98686',
      assistive: '#FBABAB',
      subtle: '#FDE3E3',
      subtler: '#FFF8F5',
    },
    warning: {
      bolder: '#966412',
      bold: '#C58218',
      normal: '#FFA91F',
      neutral: '#FFBC52',
      alternative: '#FFCC7A',
      assistive: '#FFDCA3',
      subtle: '#FFF3E0',
      subtler: '#FFFBF5',
    },
    success: {
      bolder: '#166321',
      bold: '#1C822C',
      normal: '#42B353',
      neutral: '#56BC66',
      alternative: '#7ECB8A',
      assistive: '#A6DBAE',
      subtle: '#E1F3E3',
      subtler: '#F5FBF6',
    },
    info: {
      bolder: '#183696',
      bold: '#1F46C5',
      normal: '#295BFF',
      neutral: '#5980FF',
      alternative: '#809EFF',
      assistive: '#A7BCFF',
      subtle: '#E1E8FF',
      subtler: '#F5F7FF',
    },
  },
  theme: {
    orange: {
      bolder: '#683011',
      bold: '#C55A21',
      normal: '#FF752B',
      neutral: '#FF945B',
      alternative: '#FFAD81',
      assistive: '#FFD3BB',
      subtle: '#FFECE2',
      subtler: '#FFF8F5',
    },
    yellow: {
      bolder: '#66602D',
      bold: '#CEC25A',
      normal: '#F9EB6F',
      neutral: '#FAEF8F',
      alternative: '#FBF3AA',
      assistive: '#FDF8D1',
      subtle: '#FEFCEB',
      subtler: '#FEFEF8',
    },
    sky: {
      bolder: '#184568',
      bold: '#2D83C5',
      normal: '#3BAAFF',
      neutral: '#67BDFF',
      alternative: '#8BCDFF',
      assistive: '#C0E4FF',
      subtle: '#E4F3FF',
      subtler: '#F6FBFF',
    },
  },
  system: {
    white: '#FFFFFF',
    black: '#000000',
  },
} as const;

export { semantic };
