import profileImage from '@/shared/assets/images/profileImage.png';

import {
  AtmosphereAndFocus,
  EnvironmentAndComfort,
  OtherTags,
  SeatingAndSpace,
  WorkConvenience,
} from './place-tag';
import { type FeedPost } from './types';

const FEED_CAROUSEL_IMAGES = [
  'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&h=800&fit=crop',
  'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=800&fit=crop',
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=800&fit=crop',
];

const profileImageSrc = profileImage.src;

export const MOCK_FEED_DATA: FeedPost[] = [
  {
    postId: 1,
    name: '승민',
    profileImage: profileImageSrc,
    createAt: '2026-04-26T16:54:45.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 213219,
    title: '동네 카페 작업 일지',
    contents:
      '광화문 근처에서 작업하기 좋은 곳을 드디어 찾았다. 재즈 음악이 흐르지만 소음이 적당해서 집중하기 딱 좋다.',
    placeName: '스타벅스 광화문점',
    studyTime: 150,
    focus: 4,
    tags: [
      AtmosphereAndFocus.GOOD_VIBE,
      WorkConvenience.LAPTOP_FRIENDLY,
      EnvironmentAndComfort.GOOD_SUNLIGHT,
      SeatingAndSpace.MANY_SEATS,
      AtmosphereAndFocus.MODERATE_NOISE,
    ],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 2,
    name: '감자쿵야',
    profileImage: profileImageSrc,
    createAt: '2026-04-26T16:52:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 24,
    title: '조용한 도서관 라운지 발견',
    contents:
      '주말 오전에 들렀는데 좌석 간 간격이 넓고 콘센트도 가까워서 노트북 작업하기 편했다.',
    placeName: '시청 북라운지',
    studyTime: 190,
    focus: 5,
    tags: [
      AtmosphereAndFocus.QUIET,
      SeatingAndSpace.COMFORTABLE_SEATS,
      WorkConvenience.MANY_OUTLETS,
    ],
    like: false,
    bookMark: false,
    placeCategory: '도서관',
  },
  {
    postId: 3,
    name: '도윤',
    profileImage: profileImageSrc,
    createAt: '2026-04-26T16:43:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 17,
    title: '비 오는 날엔 이 카페',
    contents:
      '창문이 크게 나 있어서 비 오는 풍경을 보며 작업하기 좋았다. 플레이리스트도 잔잔해서 마음에 들었다.',
    placeName: '레인드롭 카페',
    studyTime: 105,
    focus: 3,
    tags: [
      AtmosphereAndFocus.SCENIC,
      AtmosphereAndFocus.COZY,
      AtmosphereAndFocus.TRANQUIL,
    ],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 4,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-26T15:56:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 31,
    title: '콘센트 맛집 작업 공간',
    contents:
      '노트북이랑 태블릿을 같이 써야 해서 콘센트 위치가 중요했는데 자리 배치가 좋아서 오래 앉아도 편했다.',
    placeName: '워크룸 성수',
    studyTime: 1440,
    focus: 2,
    tags: [
      WorkConvenience.MANY_OUTLETS,
      WorkConvenience.LAPTOP_FRIENDLY,
      WorkConvenience.LONG_WORK,
    ],
    like: false,
    bookMark: false,
    placeCategory: '사무실',
  },
  {
    postId: 5,
    name: '지후',
    profileImage: profileImageSrc,
    createAt: '2026-04-26T15:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 8,
    title: '짧게 몰입하기 좋았던 곳',
    contents:
      '잠깐 할 일 정리하려고 들어갔는데 예상보다 집중이 잘 됐다. 매장 동선도 단순해서 편했다.',
    placeName: '카페 모먼트',
    studyTime: 80,
    focus: 2,
    tags: [
      AtmosphereAndFocus.IMMERSIVE,
      WorkConvenience.SHORT_WORK,
      SeatingAndSpace.CONVENIENT_LAYOUT,
    ],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 6,
    name: '서윤',
    profileImage: profileImageSrc,
    createAt: '2026-04-26T14:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 42,
    title: '오전 집중력이 잘 나왔던 스팟',
    contents:
      '햇살이 부드럽게 들어와서 기분 좋게 시작할 수 있었다. 테이블도 넓어서 책과 노트북을 같이 펼치기 좋았다.',
    placeName: '라이트업 커피',
    studyTime: 170,
    focus: 4,
    tags: [
      EnvironmentAndComfort.GOOD_SUNLIGHT,
      AtmosphereAndFocus.GOOD_FOR_FOCUS,
      SeatingAndSpace.LARGE_TABLES,
    ],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 7,
    name: '예준',
    profileImage: profileImageSrc,
    createAt: '2026-04-26T13:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 13,
    title: '사람은 많지만 집중되는 분위기',
    contents:
      '적당한 생활 소음 덕분에 오히려 더 몰입됐다. 주변에도 혼자 작업하는 사람이 많아서 분위기가 좋았다.',
    placeName: '브루클린 로스터스',
    studyTime: 135,
    focus: 4,
    tags: [
      AtmosphereAndFocus.MODERATE_NOISE,
      AtmosphereAndFocus.IMMERSIVE,
      AtmosphereAndFocus.GOOD_VIBE,
    ],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 8,
    name: '가은',
    profileImage: profileImageSrc,
    createAt: '2026-04-25T19:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 27,
    title: '팀플 준비하기 괜찮은 좌석 구성',
    contents:
      '혼자 정리하는 시간도 좋았지만 둘이 같이 와서 이야기 나누기에도 괜찮겠다는 생각이 들었다.',
    placeName: '커먼테이블 을지로',
    studyTime: 205,
    focus: 5,
    tags: [
      SeatingAndSpace.COMFORTABLE_SEATS,
      SeatingAndSpace.LARGE_TABLES,
      OtherTags.CONVERSATION_FRIENDLY,
    ],
    like: false,
    bookMark: false,
    placeCategory: '공유 오피스',
  },
  {
    postId: 9,
    name: '현우',
    profileImage: profileImageSrc,
    createAt: '2026-04-25T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 19,
    title: '재방문 확정한 저녁 작업 장소',
    contents:
      '조명이 너무 어둡지 않아서 작업하기 편했고 와이파이도 안정적으로 유지돼서 만족스러웠다.',
    placeName: '문라이트 스터디카페',
    studyTime: 160,
    focus: 4,
    tags: [
      EnvironmentAndComfort.BRIGHT_LIGHTING,
      WorkConvenience.FAST_WIFI,
      AtmosphereAndFocus.GOOD_FOR_FOCUS,
    ],
    like: false,
    bookMark: false,
    placeCategory: '스터디 카페',
  },
  {
    postId: 10,
    name: '채원',
    profileImage: profileImageSrc,
    createAt: '2026-04-24T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 35,
    title: '창가 자리가 특히 좋았던 곳',
    contents:
      '오후 햇빛이 비치는 시간대에 앉았는데 공간 분위기가 정말 좋아서 시작부터 만족스러웠다.',
    placeName: '플로우 커피하우스',
    studyTime: 180,
    focus: 4,
    tags: [
      SeatingAndSpace.WINDOW_SEATS,
      EnvironmentAndComfort.GOOD_SUNLIGHT,
      AtmosphereAndFocus.GOOD_VIBE,
    ],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 11,
    name: '유진',
    profileImage: profileImageSrc,
    createAt: '2026-04-20T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 61,
    title: '회의 전 빠르게 정리하기 좋은 라운지',
    contents:
      '미팅 전에 잠깐 정리할 곳이 필요했는데 좌석이 편하고 주변이 조용해서 짧은 시간에도 효율이 잘 나왔다.',
    placeName: '센트럴 라운지',
    studyTime: 55,
    focus: 3,
    tags: [
      AtmosphereAndFocus.QUIET,
      SeatingAndSpace.COMFORTABLE_SEATS,
      WorkConvenience.SHORT_WORK,
    ],
    like: false,
    bookMark: false,
    placeCategory: '사무실',
  },
  {
    postId: 12,
    name: '정우',
    profileImage: profileImageSrc,
    createAt: '2026-04-19T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 5,
    title: '조도 낮은 공간 좋아하면 추천',
    contents:
      '조명이 차분해서 저녁 시간에 머리 식히며 정리하기 좋았다. 음악도 과하지 않아서 흐름이 깨지지 않았다.',
    placeName: '어스톤 북카페',
    studyTime: 95,
    focus: 3,
    tags: [
      EnvironmentAndComfort.DARK_LIGHTING,
      AtmosphereAndFocus.CALM,
      AtmosphereAndFocus.GOOD_FOR_FOCUS,
    ],
    like: false,
    bookMark: false,
    placeCategory: '도서관',
  },
  {
    postId: 13,
    name: '소연',
    profileImage: profileImageSrc,
    createAt: '2026-04-18T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 88,
    title: '자료 조사할 때 다시 오고 싶은 곳',
    contents:
      '검색하고 메모하는 흐름이 끊기지 않을 만큼 자리가 안정적이었다. 오래 있어도 꽤 편했다.',
    placeName: '아카이브 카페',
    studyTime: 220,
    focus: 4,
    tags: [
      WorkConvenience.FAST_WIFI,
      SeatingAndSpace.COMFORTABLE_SEATS,
      WorkConvenience.LONG_WORK,
    ],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 14,
    name: '태윤',
    profileImage: profileImageSrc,
    createAt: '2026-04-13T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 22,
    title: '노트 필기하기 편했던 큰 테이블',
    contents:
      '노트북 옆에 공책까지 펼쳐야 해서 넓은 자리가 필요했는데 여기 테이블이 딱 좋았다.',
    placeName: '오브제 커피랩',
    studyTime: 125,
    focus: 4,
    tags: [SeatingAndSpace.LARGE_TABLES, WorkConvenience.LAPTOP_FRIENDLY],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 15,
    name: '다은',
    profileImage: profileImageSrc,
    createAt: '2026-04-06T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 140,
    title: '몰입감이 오래 유지된 조용한 공간',
    contents:
      '처음 앉고 나서 한 번도 산만해지지 않을 정도로 전체 분위기가 차분했다. 긴 작업 세션에도 좋았다.',
    placeName: '하버 스터디룸',
    studyTime: 260,
    focus: 5,
    tags: [
      AtmosphereAndFocus.IMMERSIVE,
      AtmosphereAndFocus.QUIET,
      WorkConvenience.LONG_WORK,
    ],
    like: false,
    bookMark: false,
    placeCategory: '스터디 카페',
  },
  {
    postId: 16,
    name: '준호',
    profileImage: profileImageSrc,
    createAt: '2026-04-05T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 16,
    title: '오후에 사람 빠질 때가 진짜 좋다',
    contents:
      '오후 늦게부터 한결 여유로워졌다. 그 시간대부터는 집중 흐름이 훨씬 좋아서 다음에도 그때 오고 싶다.',
    placeName: '레이어드 커피',
    studyTime: 130,
    focus: 3,
    tags: [AtmosphereAndFocus.PEACEFUL, AtmosphereAndFocus.GOOD_FOR_FOCUS],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 17,
    name: '연우',
    profileImage: profileImageSrc,
    createAt: '2026-03-27T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 77,
    title: '30일 이후 달 전 케이스 확인용',
    contents:
      '달 전 표기가 자연스럽게 보이는지 확인하려고 시간을 다양하게 넣어봤다.',
    placeName: '테스트 스팟 A',
    studyTime: 110,
    focus: 4,
    tags: [AtmosphereAndFocus.GOOD_VIBE],
    like: false,
    bookMark: false,
    placeCategory: '기타 장소',
  },
  {
    postId: 18,
    name: '수빈',
    profileImage: profileImageSrc,
    createAt: '2026-03-12T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 54,
    title: '45일 전 데이터도 자연스럽게 보이는지',
    contents:
      '상대 시간 포맷은 경계값에서 어색해지기 쉬워서 45일 정도 케이스도 넣어두는 편이 도움이 된다.',
    placeName: '테스트 스팟 B',
    studyTime: 120,
    focus: 3,
    tags: [AtmosphereAndFocus.CALM],
    like: false,
    bookMark: false,
    placeCategory: '공유 오피스',
  },
  {
    postId: 19,
    name: '시우',
    profileImage: profileImageSrc,
    createAt: '2026-02-25T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 92,
    title: '두 달 전 느낌 점검',
    contents:
      '두 달 전 같은 문구가 카드 텍스트 길이 안에서 안정적으로 보이는지 같이 보려고 넣은 샘플이다.',
    placeName: '테스트 스팟 C',
    studyTime: 185,
    focus: 5,
    tags: [AtmosphereAndFocus.GOOD_FOR_FOCUS],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 20,
    name: '은호',
    profileImage: profileImageSrc,
    createAt: '2026-01-26T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 38,
    title: '세 달 전 예시 데이터',
    contents:
      '주 단위에서 달 단위로 넘어가는 체감이 중요해서 오래된 기록도 함께 보는 게 좋다.',
    placeName: '테스트 스팟 D',
    studyTime: 75,
    focus: 2,
    tags: [AtmosphereAndFocus.QUIET],
    like: false,
    bookMark: false,
    placeCategory: '사무실',
  },
  {
    postId: 21,
    name: '지안',
    profileImage: profileImageSrc,
    createAt: '2025-12-27T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 64,
    title: '네 달 전 카드도 섞어두기',
    contents:
      '목업 검수에서는 최근 데이터만 보기 쉬운데 오래된 상대 시간도 같이 보는 편이 안전하다.',
    placeName: '테스트 스팟 E',
    studyTime: 150,
    focus: 4,
    tags: [AtmosphereAndFocus.CALM],
    like: false,
    bookMark: false,
    placeCategory: '도서관',
  },
  {
    postId: 22,
    name: '재민',
    profileImage: profileImageSrc,
    createAt: '2025-10-28T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 11,
    title: '반년 전 케이스도 확인',
    contents: '반년 전은 숫자가 조금 커지기 시작해서 시선 분산이 생길 수 있다.',
    placeName: '테스트 스팟 F',
    studyTime: 165,
    focus: 3,
    tags: [AtmosphereAndFocus.GOOD_VIBE],
    like: false,
    bookMark: false,
    placeCategory: '공유 오피스',
  },
  {
    postId: 23,
    name: '나윤',
    profileImage: profileImageSrc,
    createAt: '2025-08-29T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 29,
    title: '8개월 전 표시 확인',
    contents:
      '8달 전 같은 케이스도 실제로는 자주 보이기 때문에 헤더가 안정적으로 보이는지 체크했다.',
    placeName: '테스트 스팟 G',
    studyTime: 115,
    focus: 2,
    tags: [AtmosphereAndFocus.QUIET],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 24,
    name: '서하',
    profileImage: profileImageSrc,
    createAt: '2025-06-30T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 102,
    title: '10개월 전 데이터 샘플',
    contents:
      '10달 전 문구가 시각적으로 너무 튀지 않는지도 같이 볼 수 있도록 넣어둔 샘플이다.',
    placeName: '테스트 스팟 H',
    studyTime: 200,
    focus: 5,
    tags: [AtmosphereAndFocus.GOOD_FOR_FOCUS],
    like: false,
    bookMark: false,
    placeCategory: '스터디 카페',
  },
  {
    postId: 25,
    name: '민재',
    profileImage: profileImageSrc,
    createAt: '2025-04-27T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 46,
    title: '거의 1년 전 직전 데이터',
    contents:
      '연 전으로 넘어가기 직전 숫자도 확인하면 경계에서 기대한 표현이 나오는지 확실히 볼 수 있다.',
    placeName: '테스트 스팟 I',
    studyTime: 155,
    focus: 4,
    tags: [AtmosphereAndFocus.IMMERSIVE],
    like: false,
    bookMark: false,
    placeCategory: '기타 장소',
  },
  {
    postId: 26,
    name: '아윤',
    profileImage: profileImageSrc,
    createAt: '2025-04-26T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 58,
    title: '딱 1년 전 케이스',
    contents:
      '1년 전으로 바뀌는 지점은 제품에서 자주 체크하는 경계라서 의도적으로 분리해두는 게 좋다.',
    placeName: '테스트 스팟 J',
    studyTime: 100,
    focus: 3,
    tags: [AtmosphereAndFocus.GOOD_VIBE],
    like: false,
    bookMark: false,
    placeCategory: '사무실',
  },
  {
    postId: 27,
    name: '선우',
    profileImage: profileImageSrc,
    createAt: '2025-03-22T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 25,
    title: '1년 조금 지난 기록',
    contents:
      '365일 이후와 400일 이후가 모두 1년 전으로 보일 텐데 이게 의도된 동작인지 확인하기 위한 데이터다.',
    placeName: '테스트 스팟 K',
    studyTime: 125,
    focus: 3,
    tags: [AtmosphereAndFocus.QUIET],
    like: false,
    bookMark: false,
    placeCategory: '도서관',
  },
  {
    postId: 28,
    name: '주원',
    profileImage: profileImageSrc,
    createAt: '2024-12-12T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 71,
    title: '500일 전 기록 샘플',
    contents:
      '연 단위 표기는 숫자 변화가 느리기 때문에 오래된 기록 여러 개를 함께 섞어볼 필요가 있다.',
    placeName: '테스트 스팟 L',
    studyTime: 195,
    focus: 4,
    tags: [AtmosphereAndFocus.CALM],
    like: false,
    bookMark: false,
    placeCategory: '공유 오피스',
  },
  {
    postId: 29,
    name: '하준',
    profileImage: profileImageSrc,
    createAt: '2024-04-26T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 90,
    title: '2년 전 표시 예시',
    contents:
      '2년 전 문구는 한눈에 오래된 기록으로 보이기 때문에 헤더 정보 계층도와 함께 보는 것이 중요하다.',
    placeName: '테스트 스팟 M',
    studyTime: 175,
    focus: 5,
    tags: [AtmosphereAndFocus.GOOD_FOR_FOCUS],
    like: false,
    bookMark: false,
    placeCategory: '기타 장소',
  },
  {
    postId: 30,
    name: '다온',
    profileImage: profileImageSrc,
    createAt: '2023-01-13T18:55:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 14,
    title: '3년 전까지도 UI 확인',
    contents:
      '3년 전 정도까지 가도 헤더가 무너지지 않는지 보려고 넣은 마지막 목데이터다.',
    placeName: '테스트 스팟 N',
    studyTime: 85,
    focus: 2,
    tags: [AtmosphereAndFocus.QUIET],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 31,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-20T10:00:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 12,
    title: '조용한 카공 스팟 발견',
    contents:
      '사람이 많지 않아서 집중하기 좋았고 의자도 편해서 오래 작업 가능했음.',
    placeName: '카페 블루',
    studyTime: 120,
    focus: 4,
    tags: [AtmosphereAndFocus.QUIET, SeatingAndSpace.COMFORTABLE_SEATS],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 32,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-21T12:30:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 45,
    title: '뷰 좋은 작업 공간',
    contents: '창가 자리에서 작업하면 기분도 좋아지고 집중도 잘됨.',
    placeName: '뷰포인트 카페',
    studyTime: 210,
    focus: 3,
    tags: [AtmosphereAndFocus.SCENIC, SeatingAndSpace.WINDOW_SEATS],
    like: true,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 33,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-22T09:20:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 27,
    title: '24시간 작업 가능한 곳',
    contents: '늦게까지 작업해야 할 때 최고. 콘센트도 넉넉함.',
    placeName: '스터디허브',
    studyTime: 300,
    focus: 5,
    tags: [OtherTags.OVERNIGHT_WORK, WorkConvenience.MANY_OUTLETS],
    like: false,
    bookMark: true,
    placeCategory: '스터디카페',
  },
  {
    postId: 34,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-23T14:00:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 18,
    title: '자리 간격 넓은 카페',
    contents: '옆 사람 신경 안 쓰이고 집중하기 좋았음.',
    placeName: '카페 스페이스',
    studyTime: 240,
    focus: 4,
    tags: [
      SeatingAndSpace.WIDE_SEAT_SPACING,
      SeatingAndSpace.COMFORTABLE_SEATS,
    ],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 35,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-24T16:10:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 63,
    title: '조명 좋은 작업 공간',
    contents: '눈 피로 덜해서 오래 작업하기 좋았음.',
    placeName: '라이트 카페',
    studyTime: 180,
    focus: 5,
    tags: [
      EnvironmentAndComfort.BRIGHT_LIGHTING,
      AtmosphereAndFocus.GOOD_FOR_FOCUS,
    ],
    like: true,
    bookMark: true,
    placeCategory: '카페',
  },
  {
    postId: 36,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-25T11:40:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 9,
    title: '사람 적은 숨은 카페',
    contents: '조용해서 집중하기 좋았고 음악도 잔잔함.',
    placeName: '히든카페',
    studyTime: 150,
    focus: 4,
    tags: [
      AtmosphereAndFocus.QUIET,
      AtmosphereAndFocus.PEACEFUL,
      EnvironmentAndComfort.GOOD_SUNLIGHT,
      SeatingAndSpace.SPACIOUS,
    ],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 37,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-26T08:30:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 22,
    title: '콘센트 넉넉한 카페',
    contents: '자리마다 콘센트 있어서 충전 걱정 없음.',
    placeName: '플러그 카페',
    studyTime: 270,
    focus: 5,
    tags: [WorkConvenience.MANY_OUTLETS, WorkConvenience.CHARGING_AVAILABLE],
    like: true,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 38,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-26T18:00:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 14,
    title: '테이블 넓어서 좋음',
    contents: '노트북 + 태블릿 같이 쓰기 편함.',
    placeName: '워크존',
    studyTime: 180,
    focus: 4,
    tags: [SeatingAndSpace.LARGE_TABLES, WorkConvenience.LAPTOP_FRIENDLY],
    like: false,
    bookMark: true,
    placeCategory: '카페',
  },
  {
    postId: 39,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-27T09:10:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 7,
    title: '가성비 좋은 카페',
    contents: '가격도 저렴하고 오래 앉아도 눈치 안 보임.',
    placeName: '데일리 카페',
    studyTime: 120,
    focus: 3,
    tags: [AtmosphereAndFocus.GOOD_VIBE, WorkConvenience.LONG_WORK],
    like: false,
    bookMark: false,
    placeCategory: '카페',
  },
  {
    postId: 40,
    name: 'zl존하민ㅋ',
    profileImage: profileImageSrc,
    createAt: '2026-04-27T20:00:00.000Z',
    postImages: FEED_CAROUSEL_IMAGES,
    likes: 55,
    title: '집중 잘 되는 스터디카페',
    contents: '칸막이 있어서 집중력 최고. 시험기간 추천.',
    placeName: '스터디존',
    studyTime: 360,
    focus: 5,
    tags: [AtmosphereAndFocus.GOOD_FOR_FOCUS, AtmosphereAndFocus.IMMERSIVE],
    like: true,
    bookMark: true,
    placeCategory: '스터디카페',
  },
];
