const SERVER_URL = (process.env.NEXT_PUBLIC_SERVER_URL ?? '').replace(
  /\/$/,
  '',
);

export const BASE_URL = `${SERVER_URL}/api`;

export const CLIENT_BASE_URL = '/api';

export const KAKAO_LOGIN_URL = `${SERVER_URL}/oauth2/authorization/kakao`;

export const API_ERROR_CODE = {
  INVALID_ACCESS_PATH: 'E400',
  REQUIRED_AUTH: 'E401',
  FAILED_AUTH: 'E403',
  NOT_FOUND: 'E404',
  ALREADY_REGISTERED_MEMBER: 'E409',
  SERVER_ERROR: 'E500',
  INVALID_AUTH_HEADER: 'E1000',
  INVALID_SIGNUP_TOKEN: 'E1001',
  INVALID_REFRESH_TOKEN: 'E1002',
  EXPIRED_REFRESH_TOKEN: 'E1003',
  INVALID_NICKNAME_FORMAT: 'E1004',
  DUPLICATE_NICKNAME: 'E1005',
  INVALID_INTRODUCTION_FORMAT: 'E1006',
  CONTAINS_BAD_WORD: 'E1007',
  MEMBER_NOT_FOUND: 'E404',
  FILE_EMPTY: 'E1100',
  FILE_TYPE_INVALID: 'E1101',
  FILE_SIZE_EXCEEDED: 'E1102',
  FILE_UPLOAD_FAILED: 'E1103',
  POST_IMAGE_LIMIT_EXCEEDED: 'E1104',
  INVALID_DEFAULT_IMAGE_URL: 'E1105',
  TERMS_NOT_FOUND: 'E404',
  REQUIRED_TERMS_NOT_AGREED: 'E400',
  BADGE_NOT_FOUND: 'E1200',
  BADGE_NOT_OWNED: 'E1201',
  TAG_LIMIT_EXCEEDED: 'E1300',
  TAG_NOT_FOUND: 'E404',
  INVALID_TITLE_LENGTH: 'E1400',
  INVALID_CONTENTS_LENGTH: 'E1401',
  POST_NOT_FOUND: 'E404',
  PLACE_NOT_FOUND: 'E404',
  CATEGORY_NOT_FOUND: 'E404',
} as const;
